apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-agent-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langchain-agent-app
  template:
    metadata:
      labels:
        app: langchain-agent-app
    spec:
      containers:
        - name: langchain-agent-app
          image: ocir.sa-saopaulo-1.oci.oraclecloud.com/grm80o6tb9b2/langchain-agent-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: langchain-agent-app-secrets
      imagePullSecrets:
        - name: ocirsecret
