apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain-agent-app
  template:
    metadata:
      labels:
        app: langchain-agent-app
    spec:
      containers:
        - name: langchain-agent-app
          image: ocir.sa-saopaulo-1.oci.oraclecloud.com/grm80o6tb9b2/langchain-agent-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: langchain-agent-app-secrets
          resources:
            requests:
              cpu: "2"  
              memory: "4Gi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
              ephemeral-storage: "4Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
      imagePullSecrets:
        - name: ocirsecret
      restartPolicy: Always
