apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain-agent-app
  template:
    metadata:
      labels:
        app: langchain-agent-app
    spec:
      containers:
        - name: langchain-agent-app
          image: ocir.sa-saopaulo-1.oci.oraclecloud.com/grm80o6tb9b2/langchain-agent-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: langchain-agent-app-secrets
          resources:
            requests:
              cpu: "4"  # Ensures the pod gets at least 4 CPUs
              memory: "16Gi"  # Ensures the pod gets at least 16GB RAM
              ephemeral-storage: "4Gi"  # Prevents eviction due to disk pressure
            limits:
              cpu: "4"  # Maximum allowed CPU usage
              memory: "16Gi"  # Maximum allowed memory usage
              ephemeral-storage: "8Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
      imagePullSecrets:
        - name: ocirsecret
      restartPolicy: Always
