apiVersion: v1
kind: Service
metadata:
  name: langchain-agent-service
spec:
  selector:
    app: langchain-agent-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer