apiVersion: v1
kind: Service
metadata:
  name: langchain-agent-app
spec:
  type: NodePort
  selector:
    app: langchain-agent-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008
