name: Build and Deploy to Oracle Kubernetes

on:
  push:
    branches:
      - release/1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # ✅ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Log in to Oracle Cloud Registry (OCR)
      - name: Log in to Oracle Cloud Registry
        run: echo "${{ secrets.OCR_AUTH_TOKEN }}" | docker login ocir.sa-saopaulo-1.oci.oraclecloud.com -u "${{ secrets.OCR_USERNAME }}" --password-stdin

      # ✅ Build the Docker image
      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ocir.sa-saopaulo-1.oci.oraclecloud.com/grm80o6tb9b2/langchain-agent-app:latest --push .

      # ✅ Set up Kubernetes (kubectl)
      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # ✅ Apply Kubernetes Deployment
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment langchain-agent-app
